apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kube-pers-volumes-claim
spec:
  volumeName: kube-pers-volumes
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # less or equal to capacity storage in persistent volume 