apiVersion: v1
kind: PersistentVolume
metadata:
  name: kube-pers-volumes
spec:
  capacity: 
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce # Read Write Access for Single Node Environment
    # - ReadOnlyMany # Read Only for Multiple Nodes Environment
    # - ReadWriteMnay # Read Write for Multiple Nodes Environment
  hostPath:
    path: /data
    type: DirectoryOrCreate