apiVersion: apps/v1
kind: Deployment # type of resource
metadata:
  name: second-app-deployment
spec:
  replicas: 1 # replicas to create of Pod
  selector:
    matchLabels: # run Pods with these labels
      app: second-app
      tier: backend
  template:
    metadata: 
      labels: # to tag a Pod with labels
        app: second-app
        tier: backend
    spec: # specification of Pod
      containers: # list of containers
        - name: second-node
          image: kaushalnile/kube-setup
          imagePullPolicy: Always
          livenessProbe: # health check configurations
            httpGet:
              path: /
              port: 8080
            periodSeconds: 10
            initialDelaySeconds: 5
        # - name: ...
        #   image: ...
