apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector: # labels list to serve for
    app: second-app
  ports: # list of ports
    - protocol: 'TCP'
      port: 80
      targetPort: 8080
    # - protocol: 'TCP'
    #   port: 443
    #   targetPort: 443
  type: LoadBalancer